# Funding options for OctarqVault
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Jungley8]
ko_fi: jungley
patreon: jungley
